apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: component-sample
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: FOO
          value: BAR
        image: maysunfaisal/springboot:aug21
        name: my-java-springboot
        resources:
          limits:
            cpu: "2"
            memory: 500Mi
            storage: 400Mi
          requests:
            cpu: 700m
            memory: 400Mi
            storage: 200Mi
status: {}
